"use client";
import { useEffect,useState } from 'react';
import { api } from '@/lib/api';
export default function Widget(){
 const [source,setSource]=useState('widget'); const [sent,setSent]=useState(false); const [error,setError]=useState('');
 const [f,setF]=useState({first_name:'',last_name:'',email:'',phone:'',postal_code:'79761',city:'Waldshut-Tiengen',consent_marketing:false,consent_partner_sharing:false});
 useEffect(()=>{setSource(new URLSearchParams(window.location.search).get('source')||'widget')},[]);
 const submit=async()=>{setError('');if(!f.consent_marketing||!f.consent_partner_sharing){setError('Bitte beide Einwilligungen bestätigen.');return;}try{await api('/api/widget/leads',{method:'POST',body:JSON.stringify({...f,source_id:source,street:null,house_number:null,orientation:'unknown',shading:'unknown',annual_consumption_kwh:2500,electricity_price_eur_kwh:0.34,installation_location:'balcony',owner_status:'unknown',wants_installation:false,purchase_timeframe:'information',product_preference:'consultation',contact_time:'unknown',review_confirmed:true,consent_text_version:'widget-v2'})});setSent(true)}catch{setError('Anfrage konnte nicht gesendet werden.')}};
 if(sent)return <div className="widget-shell"><div className="kicker">Anfrage gesendet</div><h2>Danke.</h2></div>;
 return <div className="widget-shell"><div className="brand">Solar<span>Lead</span></div><h2>Balkon-PV prüfen</h2><p className="small">Kostenlose regionale Ersteinschätzung.</p><div className="grid2"><div className="field"><label>Vorname</label><input value={f.first_name} onChange={e=>setF({...f,first_name:e.target.value})}/></div><div className="field"><label>Nachname</label><input value={f.last_name} onChange={e=>setF({...f,last_name:e.target.value})}/></div></div><div className="field"><label>E-Mail</label><input value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></div><div className="field"><label>Telefon</label><input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></div>
 <label className="checkbox"><input type="checkbox" checked={f.consent_partner_sharing} onChange={e=>setF({...f,consent_partner_sharing:e.target.checked})}/><span className="small">Ich willige ein, dass meine Anfrage zur Angebotserstellung an passende regionale Fachpartner weitergegeben wird.</span></label>
 <label className="checkbox"><input type="checkbox" checked={f.consent_marketing} onChange={e=>setF({...f,consent_marketing:e.target.checked})}/><span className="small">Ich willige in die telefonische und elektronische Kontaktaufnahme zu meiner Anfrage ein. Widerruf jederzeit möglich.</span></label>
 <button className="btn" onClick={submit}>Kostenlos anfragen</button>{error&&<div className="error">{error}</div>}<p className="tiny">Vor Livebetrieb finalen Datenschutz- und Einwilligungstext juristisch prüfen und verlinken.</p></div>}
