"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {api,ApiError} from "@/lib/api";

type Lead={id:number;first_name:string;last_name:string;phone:string;postal_code:string;city:string;lead_score:number;lead_origin:string;client_account_id:number|null;setter_status:string;setter_attempts:number;purchase_timeframe:string;product_preference:string|null;market_code:string;status:string};
type Client={id:number;code:string;name:string;total:number;queued:number;qualified:number;script:string[]};
type Partner={id:number;name:string;active:boolean};
const outcomes=[['qualified','Qualifiziert'],['appointment','Termin'],['callback','Rückruf'],['unreachable','Nicht erreicht'],['not_interested','Kein Interesse'],['invalid','Ungültiger Kontakt']];
export default function Setter(){
 const [leads,setLeads]=useState<Lead[]>([]);const [clients,setClients]=useState<Client[]>([]);const [partners,setPartners]=useState<Partner[]>([]);const [client,setClient]=useState<number|''>('');const [selected,setSelected]=useState<Lead|null>(null);const [setter,setSetter]=useState('');const [notes,setNotes]=useState('');const [partnerId,setPartnerId]=useState<number|''>('');const [partnerConsent,setPartnerConsent]=useState(false);const [checks,setChecks]=useState({reached:false,contact_valid:true,interest_confirmed:false,project_fit_confirmed:false,decision_maker_confirmed:false,purchase_ready:false,appointment_requested:false});const [msg,setMsg]=useState('');
 const load=()=>{api<Lead[]>(`/api/admin/setter/queue${client?`?client_id=${client}`:''}`).then(x=>{setLeads(x);if(selected){setSelected(x.find(l=>l.id===selected.id)||null)}}).catch((e)=>{if(e instanceof ApiError&&e.status===401)location.href='/admin/login'});api<Client[]>('/api/admin/setter/clients').then(setClients);api<Partner[]>('/api/admin/buyers/partners?eligible=true').then(setPartners)};
 useEffect(load,[client]);
 const script=clients.find(c=>c.id===client)?.script||['Ist die Anfrage noch aktuell?','Was ist konkret geplant?','Passt das Projekt grundsätzlich?','Wer entscheidet?','Wann soll gestartet werden?','Ist ein Angebot oder Termin gewünscht?'];
 const save=async(outcome:string)=>{if(!selected||!setter.trim())return setMsg('Setter-Name fehlt.');if(partnerConsent&&!partnerId)return setMsg('Bitte konkreten Partner auswählen.');await api(`/api/admin/leads/${selected.id}/setter`,{method:'PATCH',body:JSON.stringify({setter_name:setter,...checks,outcome,notes,partner_consent_granted:partnerConsent,partner_id:partnerId||null})});setMsg('Gespeichert ✓');setNotes('');setPartnerConsent(false);setPartnerId('');load()};
 return <div className="container dashboard"><div className="topbar"><div><Link className="small" href="/admin">← Dashboard</Link><div className="brand" style={{marginTop:10}}>Setter Ops</div><p>Eigene oder vom Kunden gelieferte Leads nach festem Skript vorqualifizieren.</p></div><div className="field setter-filter"><label>Kunde</label><select value={client} onChange={e=>setClient(e.target.value?Number(e.target.value):'')}><option value="">Alle Leads</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div></div>
 <div className="setter-layout"><section className="card setter-queue"><div className="section-title">Call Queue · {leads.length}</div>{leads.map(l=><button key={l.id} className={`setter-lead ${selected?.id===l.id?'active':''}`} onClick={()=>setSelected(l)}><span><b>{l.first_name} {l.last_name}</b><small>{l.postal_code} {l.city||l.market_code} · {l.lead_origin==='client_supplied'?'Kundenlead':'Eigener Lead'}</small></span><strong>{l.lead_score}</strong></button>)}</section>
 <section className="card detail-card">{!selected?<div><div className="section-title">Lead auswählen</div><p>Wähle links den nächsten Kontakt aus.</p></div>:<><div className="qualification-head"><div><div className="section-title">{selected.first_name} {selected.last_name}</div><a className="call-btn" href={`tel:${selected.phone}`}>☎ {selected.phone}</a></div><div className="lead-score-big">{selected.lead_score}<span>/100</span></div></div>
 <div className="field"><label>Setter</label><input value={setter} onChange={e=>setSetter(e.target.value)} placeholder="Name Mitarbeiter"/></div>
 <div className="script-box"><div className="section-title">Call Script</div>{script.map((q,i)=><div key={i} className="script-line"><span>{i+1}</span><p>{q}</p></div>)}</div>
 <div className="qual-grid">{Object.entries({reached:'Person erreicht',contact_valid:'Kontaktdaten gültig',interest_confirmed:'Interesse bestätigt',project_fit_confirmed:'Projekt passt',decision_maker_confirmed:'Entscheider bestätigt',purchase_ready:'Kaufbereitschaft',appointment_requested:'Termin gewünscht'}).map(([k,v])=><label className="qual-check" key={k}><input type="checkbox" checked={(checks as any)[k]} onChange={e=>setChecks(x=>({...x,[k]:e.target.checked}))}/><span>{v}</span></label>)}</div>
 <div className="card" style={{padding:16,marginTop:16}}><div className="section-title">Partnerweitergabe</div><p className="small">Nur setzen, wenn der Kunde im Gespräch der Weitergabe an genau diesen Anbieter ausdrücklich zugestimmt hat.</p><div className="field"><label>Konkreter Fachpartner</label><select value={partnerId} onChange={e=>setPartnerId(e.target.value?Number(e.target.value):'')}><option value="">Noch keinen echten Buyer ausgewählt</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><label className="qual-check"><input type="checkbox" checked={partnerConsent} onChange={e=>setPartnerConsent(e.target.checked)}/><span>Ausdrückliche Zustimmung zur Weitergabe an den ausgewählten Partner im Gespräch erhalten</span></label></div><div className="field"><label>Notizen</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Einwände, Rückrufzeit, Bedarf, nächster Schritt…"/></div><div className="outcome-grid">{outcomes.map(([k,v])=><button key={k} className="mini-btn" onClick={()=>save(k)}>{v}</button>)}</div>{msg&&<div className="success-msg">{msg}</div>}</>}</section></div></div>
}
