"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {api,ApiError} from "@/lib/api";

type Dashboard={active_buyers:number;ready_leads:number;deliveries:number;won:number;win_rate:number|null;lead_revenue_eur:number;reported_order_value_eur:number};
type Rule={id:number;market_code:string;vertical_code:string;lead_price_eur:number;min_lead_score:number;daily_cap:number;active:boolean};
type Partner={id:number;name:string;slug:string;active:boolean;buyer_ready:boolean;contact_name:string|null;contact_email:string|null;contact_phone:string|null;website:string|null;rules:Rule[];metrics:{delivered:number;won:number;win_rate:number|null;lead_revenue_eur:number;order_value_eur:number}};
type Ready={lead:{id:number;first_name:string;last_name:string;phone:string;email:string;postal_code:string;city:string;market_code:string;vertical:string;lead_score:number;geo_fit_score:number|null;purchase_timeframe:string;product_preference:string|null;status:string};partner:{id:number;name:string}|null;rule:{id:number;price_eur:number;min_lead_score:number;daily_cap:number}|null;commercially_ready:boolean;reason:string|null};
type Delivery={id:number;lead_id:number;partner_name:string;lead_name:string;market_code:string;price_eur:number;status:string;order_value_eur:number|null;created_at:string};

export default function Buyers(){
 const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [partners,setPartners]=useState<Partner[]>([]);const [ready,setReady]=useState<Ready[]>([]);const [deliveries,setDeliveries]=useState<Delivery[]>([]);const [markets,setMarkets]=useState<any[]>([]);const [msg,setMsg]=useState('');
 const [form,setForm]=useState({name:'',contact_name:'',contact_email:'',contact_phone:'',website:'',market_code:'koeln',vertical_code:'balcony_pv',lead_price_eur:49,min_lead_score:70,daily_cap:10,notes:''});
 const load=()=>Promise.all([api<Dashboard>('/api/admin/buyers/dashboard').then(setDashboard),api<Partner[]>('/api/admin/buyers/partners').then(setPartners),api<Ready[]>('/api/admin/buyers/ready').then(setReady),api<Delivery[]>('/api/admin/buyers/deliveries').then(setDeliveries),api<any[]>('/api/platform/markets').then(setMarkets)]).catch(e=>{if(e instanceof ApiError&&e.status===401)location.href='/admin/login'});
 useEffect(()=>{load()},[]);
 const create=async()=>{if(!form.name.trim())return setMsg('Partnername fehlt.');await api('/api/admin/buyers/partners',{method:'POST',body:JSON.stringify(form)});setMsg('Buyer angelegt ✓');setForm(x=>({...x,name:'',contact_name:'',contact_email:'',contact_phone:'',website:'',notes:''}));load()};
 const deliver=async(r:Ready)=>{if(!r.partner||!r.rule||!r.commercially_ready)return;await api('/api/admin/buyers/deliveries',{method:'POST',body:JSON.stringify({lead_id:r.lead.id,partner_id:r.partner.id})});setMsg(`Lead #${r.lead.id} an ${r.partner.name} ausgeliefert ✓`);load()};
 const feedback=async(d:Delivery,outcome:string)=>{let order:number|null=null;let reason='';if(outcome==='won'){const raw=window.prompt('Gemeldeter Auftragswert in € (optional):','');order=raw?Number(raw):null}if(outcome==='rejected'){reason=window.prompt('Ablehnungsgrund (optional):','')||''}await api(`/api/admin/buyers/deliveries/${d.id}/feedback`,{method:'PATCH',body:JSON.stringify({outcome,order_value_eur:Number.isFinite(order as number)?order:null,reason,notes:''})});setMsg(`Feedback für Delivery #${d.id} gespeichert ✓`);load()};
 return <div className="container dashboard"><div className="topbar"><div><Link className="small" href="/admin">← Dashboard</Link><div className="brand" style={{marginTop:10}}>Buyer Ops</div><p>Echte Lead-Käufer, Preisregeln, Auslieferung und Abschlussfeedback.</p></div></div>
 {dashboard&&<div className="statgrid"><div className="card stat"><span>Aktive Buyer</span><strong>{dashboard.active_buyers}</strong></div><div className="card stat"><span>Freigegebene Leads</span><strong>{dashboard.ready_leads}</strong></div><div className="card stat"><span>Ausgeliefert</span><strong>{dashboard.deliveries}</strong></div><div className="card stat"><span>Lead-Umsatz</span><strong>{dashboard.lead_revenue_eur.toFixed(0)} €</strong></div></div>}
 <div className="buyer-layout">
  <section className="card detail-card"><div className="section-title">Echten Käufer anlegen</div><p className="small">Nur Unternehmen anlegen, mit denen ihr tatsächlich Leads austauschen wollt. Interne Pilotpartner erscheinen hier bewusst nicht.</p><div className="buyer-form-grid"><div className="field"><label>Unternehmen</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="z. B. Muster Solar GmbH"/></div><div className="field"><label>Ansprechpartner</label><input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></div><div className="field"><label>E-Mail</label><input value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></div><div className="field"><label>Telefon</label><input value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></div><div className="field"><label>Website</label><input value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></div><div className="field"><label>Markt</label><select value={form.market_code} onChange={e=>setForm({...form,market_code:e.target.value})}>{markets.map(m=><option key={m.code} value={m.code}>{m.name}</option>)}</select></div><div className="field"><label>Preis / Lead €</label><input type="number" value={form.lead_price_eur} onChange={e=>setForm({...form,lead_price_eur:Number(e.target.value)})}/></div><div className="field"><label>Mindestscore</label><input type="number" min="0" max="100" value={form.min_lead_score} onChange={e=>setForm({...form,min_lead_score:Number(e.target.value)})}/></div><div className="field"><label>Tageslimit</label><input type="number" value={form.daily_cap} onChange={e=>setForm({...form,daily_cap:Number(e.target.value)})}/></div></div><button className="btn" onClick={create}>Buyer anlegen</button></section>
  <section className="card detail-card"><div className="section-title">Buyer · {partners.length}</div><div className="buyer-partner-list">{partners.map(p=><div className="buyer-partner" key={p.id}><div><b>{p.name}</b><small>{p.contact_name||'kein Ansprechpartner'} · {p.contact_email||'keine E-Mail'}</small></div><div>{p.rules.map(r=><span className="source-pill" key={r.id}>{r.market_code} · ≥{r.min_lead_score} · {r.lead_price_eur} €</span>)}</div><div className="buyer-mini-metrics"><span>{p.metrics.delivered} geliefert</span><span>{p.metrics.won} gewonnen</span><span>{p.metrics.win_rate??'–'}% Win</span></div></div>)}{partners.length===0&&<p>Noch kein echter Buyer angelegt.</p>}</div></section>
 </div>
 <section className="card detail-card" style={{marginTop:16}}><div className="section-title">Sales-ready + konkret freigegeben</div><div className="table-wrap"><table><thead><tr><th>Lead</th><th>Markt</th><th>Score</th><th>Freigegebener Buyer</th><th>Preis</th><th>Aktion</th></tr></thead><tbody>{ready.map(r=><tr key={r.lead.id}><td><b>{r.lead.first_name} {r.lead.last_name}</b><br/><span className="small">#{r.lead.id} · {r.lead.purchase_timeframe}</span></td><td>{r.lead.postal_code} {r.lead.city}<br/><span className="small">{r.lead.market_code}</span></td><td><span className="badge">{r.lead.lead_score}</span></td><td>{r.partner?.name||'–'}{r.reason&&<><br/><span className="small warn-text">{r.reason}</span></>}</td><td>{r.rule?`${r.rule.price_eur} €`:'–'}</td><td><button className="mini-btn" disabled={!r.commercially_ready} onClick={()=>deliver(r)}>Lead liefern →</button></td></tr>)}</tbody></table>{ready.length===0&&<div style={{padding:18}}><p>Noch kein Lead hat Qualifizierung + konkrete Partnerfreigabe.</p></div>}</div></section>
 <section className="card detail-card" style={{marginTop:16}}><div className="section-title">Deliveries & Abschlussfeedback</div><div className="table-wrap"><table><thead><tr><th>Delivery</th><th>Lead</th><th>Buyer</th><th>Preis</th><th>Status</th><th>Feedback</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td>#{d.id}<br/><span className="small">{new Date(d.created_at).toLocaleString('de-DE')}</span></td><td>{d.lead_name} <span className="small">#{d.lead_id}</span></td><td>{d.partner_name}<br/><span className="small">{d.market_code}</span></td><td>{d.price_eur} €</td><td>{d.status}{d.order_value_eur? <><br/><span className="small">Auftrag {d.order_value_eur.toFixed(0)} €</span></>:null}</td><td><div className="delivery-actions"><button className="mini-btn" onClick={()=>feedback(d,'accepted')}>Akzeptiert</button><button className="mini-btn" onClick={()=>feedback(d,'won')}>Gewonnen</button><button className="mini-btn" onClick={()=>feedback(d,'lost')}>Verloren</button><button className="mini-btn" onClick={()=>feedback(d,'rejected')}>Abgelehnt</button></div></td></tr>)}</tbody></table></div></section>{msg&&<div className="success-msg">{msg}</div>}</div>
}
